### ISSUE TITLE
如何在vercel部署？

### ISSUE THREAD

**Issue by Cxyofficial** [share121/f1#3]
我看到仓库是基于vite编写的
咋样才能部署到vercel？

**Comment by share121** [comment]
你可以参考这篇文章 https://vitejs.dev/guide/static-deploy.html#vercel

**Comment by Cxyofficial** [comment]
部署成功 但网站UI无法渲染



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月16日(周二) 上午8:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [share121/f1] 如何在vercel部署？ (Issue #3)




 
你可以参考这篇文章 https://vitejs.dev/guide/static-deploy.html#vercel
